### PR TITLE
Added 59 new providers:

### PR DESCRIPTION
**Pull request by dieghernan**
See: https://leaflet-extras.github.io/leaflet-providers/preview

 Following #58

### CODE REVIEW

**Comment by dieghernan** [comment]
Need to change some sign

**Comment by dieghernan** [comment]
Change enconding for some attributions

**Comment by dieghernan** [comment]
Travis build of this branch:

https://travis-ci.com/dieghernan/cartography/builds/148320634

**Comment by rCarto** [comment]
Very nice! I'm going to merge the pull request. 
The only thing: some providers were already available ('osm' == 'OpenStreetMap', 'stamenbw' == 'Stamen.Watercolor'...) under other type names. I think it is better to use the original leaflet-provider names as you do. 
I'll add something to allow the previous names ("osm", "hotstyle", "hikebike", "osmgrayscale", "stamenbw", "stamenwatercolor", "cartodark", "cartolight", "opentopomap") to be used  for backward compatibility.

**Comment by dieghernan** [comment]
hi @rCarto, I also had that in mind, those are duplicates e.g cartodark & CartoDB.Dark, so backwards compatibility is ensured and also full compatibility with user already familiarised with Leaflet, I just thought that was the best way to do it

**Comment by arthurgailes** [comment]
Just wanted to say thank you both. This is extremely useful in creating publishable maps.

**Pull request merged**
