### PR TITLE
Proposal of new badges and license to repo

### PR DESCRIPTION
**Pull request by dieghernan**
Additional features that could be interesting to add - only affecting Github Repo and pkgdown site

### CODE REVIEW

**Comment by rCarto** [comment]
Thanks,
It's a bit too much badges for me though. I would only keep these two: 
CRAN/METACRAN
[minimal R version](https://cran.r-project.org/)

And for the license, my understanding of https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing is that the file is not necessary if we use a standard license. So I would not add the file.

**Comment by dieghernan** [comment]
Updated, if you wish to update

**Comment by rCarto** [comment]
Thanks, I'll merge this after merging your large PR

**Comment by rCarto** [comment]
Thanks again

**Pull request merged**
